name: Deploy app

on:
  push:
    branches: [main, stage]
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        APPS: [ api, cron, seed ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env to stage
        if: endsWith(github.ref, '/stage')
        run: |
            echo "DOCKER_IMAGE_TAG=stage" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: |
            echo "DOCKER_IMAGE_TAG=latest" >> $GITHUB_ENV
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          build-args: |
              APP=${{ matrix.APPS }}
          push: true
          tags: '${{ secrets.DOCKER_REGISTRY_URL }}/nest/${{ matrix.APPS }}:${{ env.DOCKER_IMAGE_TAG }}'
          cache-from: 'type=registry,ref=${{ secrets.DOCKER_REGISTRY_URL }}/nest/${{ matrix.APPS }}:${{ env.DOCKER_IMAGE_TAG }}-buildcache'
          cache-to: 'type=registry,ref=${{ secrets.DOCKER_REGISTRY_URL }}/nest/${{ matrix.APPS }}:${{ env.DOCKER_IMAGE_TAG }}-buildcache,mode=max'